//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skivermietung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artikel()
        {
            this.ArtikelVermietung = new HashSet<ArtikelVermietung>();
        }
    
        public int ID_Artikel { get; set; }
        public string Bezeichnung { get; set; }
        public string Farbe { get; set; }
        public string Marke { get; set; }
        public decimal PreisProTag { get; set; }
        public int KategorieId { get; set; }
    
        public virtual Kategorie Kategorie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArtikelVermietung> ArtikelVermietung { get; set; }
    }
}
