//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skivermietung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtikelVermietung
    {
        public int ID_ArtikelVermietung { get; set; }
        public int ArtikelId { get; set; }
        public int VermietungsId { get; set; }
    
        public virtual Artikel Artikel { get; set; }
        public virtual Vermietung Vermietung { get; set; }
    }
}
