//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skivermietung.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SkivermietungContext : DbContext
    {
        public SkivermietungContext()
            : base("name=SkivermietungContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Artikel> Artikel { get; set; }
        public DbSet<ArtikelVermietung> ArtikelVermietung { get; set; }
        public DbSet<Benutzer> Benutzer { get; set; }
        public DbSet<Kategorie> Kategorie { get; set; }
        public DbSet<Kunde> Kunde { get; set; }
        public DbSet<Vermietung> Vermietung { get; set; }
    }
}
