//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skivermietung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vermietung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vermietung()
        {
            this.ArtikelVermietung = new HashSet<ArtikelVermietung>();
        }
    
        public int ID_Vermietung { get; set; }
        public System.DateTime Von { get; set; }
        public System.DateTime Bis { get; set; }
        public Nullable<System.DateTime> Bezahlt { get; set; }
        public Nullable<int> Rabatt { get; set; }
        public int KundeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArtikelVermietung> ArtikelVermietung { get; set; }
        public virtual Kunde Kunde { get; set; }
    }
}
